const teachers = [
  {
    '_id': '1',
    'name': 'Juliana A.',
    'flag': 'Colombia',
    'rate': '$13/hour',
    'image': '/images/juliana.jpg',
    'teachingLanguage': 'Spanish Language',
    'speakingLanguage': 'English',
    'rating': '4.7',
    'reviews': 'numOfReviewsLink',
    'numLessons': '1,287',
    'description': 'Learn Spanish with a Native Colombian Tutor I am from Bogotá, Colombia but I have lived all over the globe whilst I teach Spanish online. Therefore, over the last 4 years I have been teaching ...',
    'video': 'embeddedVideo',
    'bookTeacher': 'linkToBook',
    'calendarPreview': 'calendarPhoto',
    'messageTeacher': 'linkToMessage'
  },
  {
    '_id': '2',
    'name': 'Angela G',
    'flag': 'Peru',
    'rate': '$5/hour',
    'image': '/images/angela.jpg',
    'teachingLanguage': 'Spanish Language',
    'speakingLanguage': 'English',
    'rating': '4.5',
    'reviews': 'numOfReviewsLink',
    'numLessons': '287',
    'description': 'Learn Spanish with a Native Colombian Tutor I am from Bogotá, Colombia but I have lived all over the globe whilst I teach Spanish online. Therefore, over the last 4 years I have been teaching ...',
    'video': 'embeddedVideo',
    'bookTeacher': 'linkToBook',
    'calendarPreview': 'calendarPhoto',
    'messageTeacher': 'linkToMessage'
  },
  {
    '_id': '3',
    'name': 'Diana J',
    'flag': 'Chile',
    'rate': '$11/hour',
    'image': '/images/dianaj.jpg',
    'teachingLanguage': 'Spanish Language',
    'speakingLanguage': 'English',
    'rating': '3.7',
    'reviews': 'numOfReviewsLink',
    'numLessons': '87',
    'description': 'I am a Native Colombian Tutor I am from Bogotá, Colombia but I have lived all over the globe whilst I teach Spanish online. Therefore, over the last 4 years I have been teaching ...',
    'video': 'embeddedVideo',
    'bookTeacher': 'linkToBook',
    'calendarPreview': 'calendarPhoto',
    'messageTeacher': 'linkToMessage'
  },
  {
    '_id': '4',
    'name': 'Lina B',
    'flag': 'Colombia',
    'rate': '$10/hour',
    'image': '/images/lina.jpg',
    'teachingLanguage': 'Spanish Language',
    'speakingLanguage': 'English',
    'rating': '4.9',
    'reviews': 'numOfReviewsLink',
    'numLessons': '3,287',
    'description': 'Learn Spanish with a Native Colombian Tutor I am from Bogotá, Colombia',
    'video': 'embeddedVideo',
    'bookTeacher': 'linkToBook',
    'calendarPreview': 'calendarPhoto',
    'messageTeacher': 'linkToMessage'
  }
]
